### ISSUE TITLE
Включення точок, які не належать до полігону

### ISSUE THREAD

**Issue by skitalets86** [DefteZ/westra2osm#1]
Валідатор включає точки, які фактично не входять до полігону, але лежать в межах крайніх вершин.

Приклад полігону:
[HIGHLIGHTING]
zoom=16
PointLon_1=77.4189112578655
PointLat_1=43.1191428653656
PointLon_2=77.4451754485393
PointLat_2=43.1195187686117
PointLon_3=77.4462054168011
PointLat_3=43.1064075131254
PointLon_4=77.428009310844
PointLat_4=43.1081153427299
PointLon_5=77.4189112578655
PointLat_5=43.1191428653656

Результат обробки:
<!DOCTYPE HTML>
<html>
<title>OSM валідатор перевалів</title>
<meta charset="utf-8">
<meta name="keywords" content="Вестра, OSM, Openstreetmap, westra, kml"> 
<body>
<b>Останній раз оновлено:</b> 2015-07-08 00:08 EET<br>
Вього перевалів в таблиці: 1<br>
    із них є тільки в Вестрі: 0<br>
    із них є тільки в OSM: 0<br>
    є в обох базах: 1<br>
<a href='https://github.com/DefteZ/westra2osm/'>Дізнаться більше про проект</a><br>
<br>

<table border>
<tr><th>Перевал в каталогі "Вестри"</th><th>Перевал в ОСМ</th></tr>        <tr><td>Кокбулак</td><td>Кокбулак (Кок-Булак)</td></tr>
    </table>

```
</body>
</html>
```

**Comment by DefteZ** [comment]
Fixed
