### ISSUE TITLE
It does not work now - AssertionError

### ISSUE THREAD

**Issue by skitalets86** [DefteZ/westra2osm#3]
Script does not work. Last version validation Ile_Alatau is 09-11-2015. Now I used new poligon Svanetia (I cannot attach hlg because don't support that file type). 
Traceback (most recent call last):
  File "pass_validator.py", line 213, in <module>
    main()
  File "pass_validator.py", line 102, in main
    assert all_westra == both_base+westra_alone, 'sometching goes wrong with Westra DB: {0} != {1}+{2}'.format(all_westra, both_base, westra_alone)  #self-check
AssertionError: sometching goes wrong with Westra DB: 17 != 4+56

**Comment by DefteZ** [comment]
Westra was add some changes to html and that break parsing.

Already fixed
